# Generated by Django 5.2.5 on 2025-08-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section 1', 'verbose_name_plural': 'Hero Sections 1'},
        ),
        migrations.AlterModelOptions(
            name='herosection2',
            options={'verbose_name': 'Hero Section 2', 'verbose_name_plural': 'Hero Sections 2'},
        ),
        migrations.RemoveField(
            model_name='galery',
            name='description',
        ),
    ]
