# Generated by Django 5.2.5 on 2025-08-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_herosection_options_alter_herosection2_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(max_length=300)),
                ('background_image', models.ImageField(upload_to='hero_backgrounds/')),
            ],
            options={
                'verbose_name': 'Hero Section - Galery',
                'verbose_name_plural': 'Hero Sections - Galery',
            },
        ),
        migrations.CreateModel(
            name='heroSection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(max_length=300)),
                ('background_image', models.ImageField(upload_to='hero_backgrounds/')),
            ],
            options={
                'verbose_name': 'Hero Section - About',
                'verbose_name_plural': 'Hero Sections - About',
            },
        ),
    ]
