# Generated by Django 5.2.5 on 2025-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_herosection3_herosection4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procediment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='procediment_images/')),
            ],
        ),
    ]
