# Generated by Django 5.2.5 on 2025-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_procediment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='galery',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, related_name='galeries', to='home.tag'),
        ),
    ]
