# Generated by Django 5.2.5 on 2025-09-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutthings_tag_galery_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='procediment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
