# Generated by Django 5.2.5 on 2025-09-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_procediment_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
