# Generated by Django 5.2.5 on 2025-09-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='about_pictures/')),
            ],
            options={
                'verbose_name': "Seção 'Sobre Nós'",
                'verbose_name_plural': "Seção 'Sobre Nós'",
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título (opcional)')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
            },
        ),
        migrations.CreateModel(
            name='GalleryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('estudio', 'Estúdio'), ('equipamentos', 'Equipamentos'), ('fotos', 'Fotos')], max_length=50, unique=True, verbose_name='Nome da Tag')),
            ],
            options={
                'verbose_name': 'Tag da Galeria',
                'verbose_name_plural': 'Tags da Galeria',
            },
        ),
        migrations.CreateModel(
            name='Hero_Section5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(max_length=300)),
                ('background_image', models.ImageField(upload_to='hero_backgrounds/')),
            ],
            options={
                'verbose_name': 'Hero Section - Procedimentos',
                'verbose_name_plural': 'Hero Sections - Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='metrics_icons/')),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_cards', to='home.about_us', verbose_name='Página Sobre Nós')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
            },
        ),
        migrations.CreateModel(
            name='Procediments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='procediment_images/')),
            ],
            options={
                'verbose_name': "Seção 'Procedimento'",
                'verbose_name_plural': " Seção 'Procedimentos'",
            },
        ),
        migrations.CreateModel(
            name='What_We_Do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='what_we_do_icons/')),
            ],
            options={
                'verbose_name': "Seção 'O Que Fazemos'",
                'verbose_name_plural': "Seção 'O Que Fazemos'",
            },
        ),
        migrations.RenameModel(
            old_name='heroSection',
            new_name='Hero_Section1',
        ),
        migrations.RenameModel(
            old_name='heroSection3',
            new_name='Hero_Section2',
        ),
        migrations.RenameModel(
            old_name='heroSection2',
            new_name='Hero_Section3',
        ),
        migrations.RenameModel(
            old_name='heroSection4',
            new_name='Hero_Section4',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='AboutThings',
        ),
        migrations.RemoveField(
            model_name='galery',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Procediment',
        ),
        migrations.AlterModelOptions(
            name='hero_section1',
            options={'verbose_name': 'Hero Section 1 - Home', 'verbose_name_plural': 'Hero Sections 1 - Home'},
        ),
        migrations.AlterModelOptions(
            name='hero_section2',
            options={'verbose_name': 'Hero Section 2 - Home', 'verbose_name_plural': 'Hero Sections 2 - Home'},
        ),
        migrations.AlterModelOptions(
            name='hero_section3',
            options={'verbose_name': 'Hero Section - Galeria', 'verbose_name_plural': 'Hero Sections - Galeria'},
        ),
        migrations.AlterModelOptions(
            name='hero_section4',
            options={'verbose_name': 'Hero Section - Sobre Nós', 'verbose_name_plural': 'Hero Sections - Sobre Nós'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='home.gallerytag', verbose_name='Tag'),
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
