# Generated by Django 5.2.5 on 2025-09-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_about_us_galleryimage_gallerytag_hero_section5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='image',
        ),
    ]
