# Generated by Django 5.2.5 on 2025-08-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_home', models.CharField(default='Lash Design', max_length=100)),
                ('site_name_about', models.CharField(default='Lash Design - Sobre', max_length=100)),
                ('site_name_galery', models.CharField(default='Lash Design - Galeria', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('whatsapp_link', models.URLField(blank=True, help_text='Ex: https://wa.me/seunumerodetelefone')),
                ('show_navbar', models.BooleanField(default=True, verbose_name='Exibir Barra de Navegação')),
                ('show_hero_section_1', models.BooleanField(default=True, verbose_name='Exibir Seção "Hero 1"')),
                ('show_about_section', models.BooleanField(default=True, verbose_name='Exibir Seção "Sobre"')),
                ('show_galery_section', models.BooleanField(default=True, verbose_name='Exibir Seção "Galeria"')),
                ('show_hero_section_2', models.BooleanField(default=True, verbose_name='Exibir Seção "Hero 2"')),
                ('show_equipaments_section', models.BooleanField(default=True, verbose_name='Exibir Seção "Equipamentos"')),
                ('show_footer', models.BooleanField(default=True, verbose_name='Exibir Rodapé')),
                ('navbar_title', models.CharField(default='Lash Design', max_length=50)),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Link')),
                ('url', models.CharField(max_length=200, verbose_name='URL do Link')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_links', to='SiteSetup.sitesettings')),
            ],
            options={
                'verbose_name': 'Link da Navbar',
                'verbose_name_plural': 'Links da Navbar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('content', models.TextField(help_text='Use HTML simples para formatação se necessário.', verbose_name='Conteúdo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_texts', to='SiteSetup.sitesettings')),
            ],
            options={
                'verbose_name': 'Conteúdo do Rodapé',
                'verbose_name_plural': 'Conteúdos do Rodapé',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Plataforma (Ex: Instagram, Facebook)')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_social_links', to='SiteSetup.sitesettings')),
            ],
            options={
                'verbose_name': 'Link Social do Rodapé',
                'verbose_name_plural': 'Links Sociais do Rodapé',
                'ordering': ['order'],
            },
        ),
    ]
