# Generated by Django 5.2.5 on 2025-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarlink',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Marque se o link for externo ao site.', verbose_name='Link Externo'),
        ),
    ]
