# Generated by Django 5.2.5 on 2025-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0002_navbarlink_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_procediments_section',
            field=models.BooleanField(default=True, verbose_name='Exibir Seção "Procedimentos"'),
        ),
    ]
