# Generated by Django 5.2.5 on 2025-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetup', '0003_sitesettings_show_procediments_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_equipaments_section',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_about_section_2',
            field=models.BooleanField(default=True, verbose_name='Exibir Seção "Página Sobre"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_galery_procediments_section',
            field=models.BooleanField(default=True, verbose_name='Exibir Seção "Galeria de Procedimentos"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_hero_section_3',
            field=models.BooleanField(default=True, verbose_name='Exibir Seção "Hero 3"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_hero_section_4',
            field=models.BooleanField(default=True, verbose_name='Exibir Seção "Hero 4"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_make_section',
            field=models.BooleanField(default=True, verbose_name='Exibir Seção "O Que Fazemos"'),
        ),
    ]
